name: Deploy to VPS

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'development' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            BRANCH="${{ github.ref_name }}"
            ENV_FILE_ARGS="--env-file .env"

            cd "${{ secrets.PROJECT_PATH }}"

            if [ -f .env.local ]; then
              ENV_FILE_ARGS="${ENV_FILE_ARGS} --env-file .env.local"
            fi

            echo "Pull latest changes from ${BRANCH} branch"
            git fetch origin "${BRANCH}"
            git checkout "${BRANCH}"
            git pull --ff-only origin "${BRANCH}"

            echo "Restart service"
            docker compose down --remove-orphans
            docker compose ${ENV_FILE_ARGS} up -d --build

            echo "Executing migrations"
            docker compose exec -T hp_app npm run migration:run:dist

            echo "Done"
